"""criação da tabela Message

Revision ID: 500154d7c7d6
Revises: 
Create Date: 2025-05-27 18:43:37.795647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500154d7c7d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
